[virtualenvs]
create = true
in-project = true
options.always-copy = true
options.no-pip = false
options.no-setuptools = false
options.system-site-packages = false
prefer-active-python = false
prompt = "{project_name}-py{python_version}"
